title: "Oscar Rojas Villarroel"
author: "Oscar Rojas"
description: "University of Texas at Austin"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
  
# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "oscarcv.pdf", title: "CV"}
  - {file: "_articles", title: "Articles"}
  - {file: "_pictures", title: "Books"}
  - {file: "_pictures", title: "Gallery"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:oscar.rojas@utexas.edu"}
  - {title: Github, icon: github, url: "https://github.com/oscarrojasv"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
